### ISSUE TITLE
Cannot install python3 on stretch due to Python locale encoding error

### ISSUE THREAD

**Issue by roosemberth** [debuerreotype/docker-debian-artifacts#8]
Build using ansible-container: (files attached)
[python3-debian.zip](https://github.com/debuerreotype/docker-debian-artifacts/files/1186888/python3-debian.zip)

```
~$ ansible-container build
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
Parsing conductor CLI args.
Docker™ daemon integration engine loaded. Build starting.       project=python3-debian
Building service...     project=python3-debian service=someservice

PLAY [someservice] *************************************************************

TASK [Gathering Facts] *********************************************************
ok: [someservice]

TASK [python3-test-role : Install python3] *************************************
fatal: [someservice]: FAILED! => {"cache_update_time": 1501451506, "cache_updated": true, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'python3'' failed: debconf: delaying package configuration, since apt-utils is not installed\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "debconf: delaying package configuration, since apt-utils is not installed\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["debconf: delaying package configuration, since apt-utils is not installed", "E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following additional packages will be installed:\n  bzip2 dh-python file libexpat1 libmagic-mgc libmagic1 libmpdec2\n  libpython3-stdlib libpython3.5-minimal libpython3.5-stdlib libreadline7\n  libsqlite3-0 libssl1.1 mime-support python3-minimal python3.5\n  python3.5-minimal readline-common xz-utils\nSuggested packages:\n  bzip2-doc libdpkg-perl python3-doc python3-tk python3-venv python3.5-venv\n  python3.5-doc binutils binfmt-support readline-doc\nThe following NEW packages will be installed:\n  bzip2 dh-python file libexpat1 libmagic-mgc libmagic1 libmpdec2\n  libpython3-stdlib libpython3.5-minimal libpython3.5-stdlib libreadline7\n  libsqlite3-0 libssl1.1 mime-support python3 python3-minimal python3.5\n  python3.5-minimal readline-common xz-utils\n0 upgraded, 20 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 7869 kB of archives.\nAfter this operation, 36.6 MB of additional disk space will be used.\nGet:1 http://deb.debian.org/debian stretch/main amd64 libssl1.1 amd64 1.1.0f-3 [1342 kB]\nGet:2 http://deb.debian.org/debian stretch/main amd64 libpython3.5-minimal amd64 3.5.3-1 [573 kB]\nGet:3 http://deb.debian.org/debian stretch/main amd64 python3.5-minimal amd64 3.5.3-1 [1688 kB]\nGet:4 http://deb.debian.org/debian stretch/main amd64 python3-minimal amd64 3.5.3-1 [35.3 kB]\nGet:5 http://deb.debian.org/debian stretch/main amd64 mime-support all 3.60 [36.7 kB]\nGet:6 http://deb.debian.org/debian stretch/main amd64 libmpdec2 amd64 2.4.2-1 [85.2 kB]\nGet:7 http://deb.debian.org/debian stretch/main amd64 readline-common all 7.0-3 [70.4 kB]\nGet:8 http://deb.debian.org/debian stretch/main amd64 libreadline7 amd64 7.0-3 [151 kB]\nGet:9 http://deb.debian.org/debian stretch/main amd64 libsqlite3-0 amd64 3.16.2-5 [572 kB]\nGet:10 http://deb.debian.org/debian stretch/main amd64 libpython3.5-stdlib amd64 3.5.3-1 [2166 kB]\nGet:11 http://deb.debian.org/debian stretch/main amd64 python3.5 amd64 3.5.3-1 [229 kB]\nGet:12 http://deb.debian.org/debian stretch/main amd64 libpython3-stdlib amd64 3.5.3-1 [18.6 kB]\nGet:13 http://deb.debian.org/debian stretch/main amd64 dh-python all 2.20170125 [86.8 kB]\nGet:14 http://deb.debian.org/debian stretch/main amd64 python3 amd64 3.5.3-1 [21.6 kB]\nGet:15 http://deb.debian.org/debian stretch/main amd64 bzip2 amd64 1.0.6-8.1 [47.5 kB]\nGet:16 http://deb.debian.org/debian stretch/main amd64 libmagic-mgc amd64 1:5.30-1 [222 kB]\nGet:17 http://deb.debian.org/debian stretch/main amd64 libmagic1 amd64 1:5.30-1 [111 kB]\nGet:18 http://deb.debian.org/debian stretch/main amd64 file amd64 1:5.30-1 [63.9 kB]\nGet:19 http://deb.debian.org/debian stretch/main amd64 xz-utils amd64 5.2.2-1.2+b1 [266 kB]\nGet:20 http://security.debian.org stretch/updates/main amd64 libexpat1 amd64 2.2.0-2+deb9u1 [83.4 kB]\nFetched 7869 kB in 40s (196 kB/s)\nSelecting previously unselected package libssl1.1:amd64.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 6491 files and directories currently installed.)\r\nPreparing to unpack .../00-libssl1.1_1.1.0f-3_amd64.deb ...\r\nUnpacking libssl1.1:amd64 (1.1.0f-3) ...\r\nSelecting previously unselected package libpython3.5-minimal:amd64.\r\nPreparing to unpack .../01-libpython3.5-minimal_3.5.3-1_amd64.deb ...\r\nUnpacking libpython3.5-minimal:amd64 (3.5.3-1) ...\r\nSelecting previously unselected package libexpat1:amd64.\r\nPreparing to unpack .../02-libexpat1_2.2.0-2+deb9u1_amd64.deb ...\r\nUnpacking libexpat1:amd64 (2.2.0-2+deb9u1) ...\r\nSelecting previously unselected package python3.5-minimal.\r\nPreparing to unpack .../03-python3.5-minimal_3.5.3-1_amd64.deb ...\r\nUnpacking python3.5-minimal (3.5.3-1) ...\r\nSelecting previously unselected package python3-minimal.\r\nPreparing to unpack .../04-python3-minimal_3.5.3-1_amd64.deb ...\r\nUnpacking python3-minimal (3.5.3-1) ...\r\nSelecting previously unselected package mime-support.\r\nPreparing to unpack .../05-mime-support_3.60_all.deb ...\r\nUnpacking mime-support (3.60) ...\r\nSelecting previously unselected package libmpdec2:amd64.\r\nPreparing to unpack .../06-libmpdec2_2.4.2-1_amd64.deb ...\r\nUnpacking libmpdec2:amd64 (2.4.2-1) ...\r\nSelecting previously unselected package readline-common.\r\nPreparing to unpack .../07-readline-common_7.0-3_all.deb ...\r\nUnpacking readline-common (7.0-3) ...\r\nSelecting previously unselected package libreadline7:amd64.\r\nPreparing to unpack .../08-libreadline7_7.0-3_amd64.deb ...\r\nUnpacking libreadline7:amd64 (7.0-3) ...\r\nSelecting previously unselected package libsqlite3-0:amd64.\r\nPreparing to unpack .../09-libsqlite3-0_3.16.2-5_amd64.deb ...\r\nUnpacking libsqlite3-0:amd64 (3.16.2-5) ...\r\nSelecting previously unselected package libpython3.5-stdlib:amd64.\r\nPreparing to unpack .../10-libpython3.5-stdlib_3.5.3-1_amd64.deb ...\r\nUnpacking libpython3.5-stdlib:amd64 (3.5.3-1) ...\r\nSelecting previously unselected package python3.5.\r\nPreparing to unpack .../11-python3.5_3.5.3-1_amd64.deb ...\r\nUnpacking python3.5 (3.5.3-1) ...\r\nSelecting previously unselected package libpython3-stdlib:amd64.\r\nPreparing to unpack .../12-libpython3-stdlib_3.5.3-1_amd64.deb ...\r\nUnpacking libpython3-stdlib:amd64 (3.5.3-1) ...\r\nSelecting previously unselected package dh-python.\r\nPreparing to unpack .../13-dh-python_2.20170125_all.deb ...\r\nUnpacking dh-python (2.20170125) ...\r\nSetting up libssl1.1:amd64 (1.1.0f-3) ...\r\nSetting up libpython3.5-minimal:amd64 (3.5.3-1) ...\r\nSetting up libexpat1:amd64 (2.2.0-2+deb9u1) ...\r\nSetting up python3.5-minimal (3.5.3-1) ...\r\nSetting up python3-minimal (3.5.3-1) ...\r\nFatal Python error: Py_Initialize: Unable to get the locale encoding\r\n  File \"/_usr/lib/python2.7/encodings/__init__.py\", line 123\r\n    raise CodecRegistryError,\\\r\n                            ^\r\nSyntaxError: invalid syntax\r\n\r\nCurrent thread 0x00007fddf78e0b40 (most recent call first):\r\nAborted (core dumped)\r\ndpkg: error processing package python3-minimal (--configure):\r\n subprocess installed post-installation script returned error exit status 134\r\nErrors were encountered while processing:\r\n python3-minimal\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following additional packages will be installed:", "  bzip2 dh-python file libexpat1 libmagic-mgc libmagic1 libmpdec2", "  libpython3-stdlib libpython3.5-minimal libpython3.5-stdlib libreadline7", "  libsqlite3-0 libssl1.1 mime-support python3-minimal python3.5", "  python3.5-minimal readline-common xz-utils", "Suggested packages:", "  bzip2-doc libdpkg-perl python3-doc python3-tk python3-venv python3.5-venv", "  python3.5-doc binutils binfmt-support readline-doc", "The following NEW packages will be installed:", "  bzip2 dh-python file libexpat1 libmagic-mgc libmagic1 libmpdec2", "  libpython3-stdlib libpython3.5-minimal libpython3.5-stdlib libreadline7", "  libsqlite3-0 libssl1.1 mime-support python3 python3-minimal python3.5", "  python3.5-minimal readline-common xz-utils", "0 upgraded, 20 newly installed, 0 to remove and 0 not upgraded.", "Need to get 7869 kB of archives.", "After this operation, 36.6 MB of additional disk space will be used.", "Get:1 http://deb.debian.org/debian stretch/main amd64 libssl1.1 amd64 1.1.0f-3 [1342 kB]", "Get:2 http://deb.debian.org/debian stretch/main amd64 libpython3.5-minimal amd64 3.5.3-1 [573 kB]", "Get:3 http://deb.debian.org/debian stretch/main amd64 python3.5-minimal amd64 3.5.3-1 [1688 kB]", "Get:4 http://deb.debian.org/debian stretch/main amd64 python3-minimal amd64 3.5.3-1 [35.3 kB]", "Get:5 http://deb.debian.org/debian stretch/main amd64 mime-support all 3.60 [36.7 kB]", "Get:6 http://deb.debian.org/debian stretch/main amd64 libmpdec2 amd64 2.4.2-1 [85.2 kB]", "Get:7 http://deb.debian.org/debian stretch/main amd64 readline-common all 7.0-3 [70.4 kB]", "Get:8 http://deb.debian.org/debian stretch/main amd64 libreadline7 amd64 7.0-3 [151 kB]", "Get:9 http://deb.debian.org/debian stretch/main amd64 libsqlite3-0 amd64 3.16.2-5 [572 kB]", "Get:10 http://deb.debian.org/debian stretch/main amd64 libpython3.5-stdlib amd64 3.5.3-1 [2166 kB]", "Get:11 http://deb.debian.org/debian stretch/main amd64 python3.5 amd64 3.5.3-1 [229 kB]", "Get:12 http://deb.debian.org/debian stretch/main amd64 libpython3-stdlib amd64 3.5.3-1 [18.6 kB]", "Get:13 http://deb.debian.org/debian stretch/main amd64 dh-python all 2.20170125 [86.8 kB]", "Get:14 http://deb.debian.org/debian stretch/main amd64 python3 amd64 3.5.3-1 [21.6 kB]", "Get:15 http://deb.debian.org/debian stretch/main amd64 bzip2 amd64 1.0.6-8.1 [47.5 kB]", "Get:16 http://deb.debian.org/debian stretch/main amd64 libmagic-mgc amd64 1:5.30-1 [222 kB]", "Get:17 http://deb.debian.org/debian stretch/main amd64 libmagic1 amd64 1:5.30-1 [111 kB]", "Get:18 http://deb.debian.org/debian stretch/main amd64 file amd64 1:5.30-1 [63.9 kB]", "Get:19 http://deb.debian.org/debian stretch/main amd64 xz-utils amd64 5.2.2-1.2+b1 [266 kB]", "Get:20 http://security.debian.org stretch/updates/main amd64 libexpat1 amd64 2.2.0-2+deb9u1 [83.4 kB]", "Fetched 7869 kB in 40s (196 kB/s)", "Selecting previously unselected package libssl1.1:amd64.", "(Reading database ... ", "(Reading database ... 5%", "(Reading database ... 10%", "(Reading database ... 15%", "(Reading database ... 20%", "(Reading database ... 25%", "(Reading database ... 30%", "(Reading database ... 35%", "(Reading database ... 40%", "(Reading database ... 45%", "(Reading database ... 50%", "(Reading database ... 55%", "(Reading database ... 60%", "(Reading database ... 65%", "(Reading database ... 70%", "(Reading database ... 75%", "(Reading database ... 80%", "(Reading database ... 85%", "(Reading database ... 90%", "(Reading database ... 95%", "(Reading database ... 100%", "(Reading database ... 6491 files and directories currently installed.)", "Preparing to unpack .../00-libssl1.1_1.1.0f-3_amd64.deb ...", "Unpacking libssl1.1:amd64 (1.1.0f-3) ...", "Selecting previously unselected package libpython3.5-minimal:amd64.", "Preparing to unpack .../01-libpython3.5-minimal_3.5.3-1_amd64.deb ...", "Unpacking libpython3.5-minimal:amd64 (3.5.3-1) ...", "Selecting previously unselected package libexpat1:amd64.", "Preparing to unpack .../02-libexpat1_2.2.0-2+deb9u1_amd64.deb ...", "Unpacking libexpat1:amd64 (2.2.0-2+deb9u1) ...", "Selecting previously unselected package python3.5-minimal.", "Preparing to unpack .../03-python3.5-minimal_3.5.3-1_amd64.deb ...", "Unpacking python3.5-minimal (3.5.3-1) ...", "Selecting previously unselected package python3-minimal.", "Preparing to unpack .../04-python3-minimal_3.5.3-1_amd64.deb ...", "Unpacking python3-minimal (3.5.3-1) ...", "Selecting previously unselected package mime-support.", "Preparing to unpack .../05-mime-support_3.60_all.deb ...", "Unpacking mime-support (3.60) ...", "Selecting previously unselected package libmpdec2:amd64.", "Preparing to unpack .../06-libmpdec2_2.4.2-1_amd64.deb ...", "Unpacking libmpdec2:amd64 (2.4.2-1) ...", "Selecting previously unselected package readline-common.", "Preparing to unpack .../07-readline-common_7.0-3_all.deb ...", "Unpacking readline-common (7.0-3) ...", "Selecting previously unselected package libreadline7:amd64.", "Preparing to unpack .../08-libreadline7_7.0-3_amd64.deb ...", "Unpacking libreadline7:amd64 (7.0-3) ...", "Selecting previously unselected package libsqlite3-0:amd64.", "Preparing to unpack .../09-libsqlite3-0_3.16.2-5_amd64.deb ...", "Unpacking libsqlite3-0:amd64 (3.16.2-5) ...", "Selecting previously unselected package libpython3.5-stdlib:amd64.", "Preparing to unpack .../10-libpython3.5-stdlib_3.5.3-1_amd64.deb ...", "Unpacking libpython3.5-stdlib:amd64 (3.5.3-1) ...", "Selecting previously unselected package python3.5.", "Preparing to unpack .../11-python3.5_3.5.3-1_amd64.deb ...", "Unpacking python3.5 (3.5.3-1) ...", "Selecting previously unselected package libpython3-stdlib:amd64.", "Preparing to unpack .../12-libpython3-stdlib_3.5.3-1_amd64.deb ...", "Unpacking libpython3-stdlib:amd64 (3.5.3-1) ...", "Selecting previously unselected package dh-python.", "Preparing to unpack .../13-dh-python_2.20170125_all.deb ...", "Unpacking dh-python (2.20170125) ...", "Setting up libssl1.1:amd64 (1.1.0f-3) ...", "Setting up libpython3.5-minimal:amd64 (3.5.3-1) ...", "Setting up libexpat1:amd64 (2.2.0-2+deb9u1) ...", "Setting up python3.5-minimal (3.5.3-1) ...", "Setting up python3-minimal (3.5.3-1) ...", "Fatal Python error: Py_Initialize: Unable to get the locale encoding", "  File \"/_usr/lib/python2.7/encodings/__init__.py\", line 123", "    raise CodecRegistryError,\\", "                            ^", "SyntaxError: invalid syntax", "", "Current thread 0x00007fddf78e0b40 (most recent call first):", "Aborted (core dumped)", "dpkg: error processing package python3-minimal (--configure):", " subprocess installed post-installation script returned error exit status 134", "Errors were encountered while processing:", " python3-minimal"]}
        to retry, use: --limit @/tmp/tmplMpR2d/playbook.retry

PLAY RECAP *********************************************************************
someservice                : ok=1    changed=0    unreachable=0    failed=1

ERROR   Error applying role!    engine=<container.docker.engine.Engine object at 0x7fbcfffe1950> exit_code=2 playbook=[{'hosts': u'someservice', 'roles': [ordereddict([('role', 'python3-test-role')])], 'vars': {}}]
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 360, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 724, in conductorcmd_build
    raise RuntimeError('Build failed.')
RuntimeError: Build failed.
Conductor terminated. Cleaning up.      command_rc=1 conductor_id=fb5f2c993660af3fe9325bcfaebd926702f1161999d96b32d5376b7daa54ea7b save_container=False
ERROR   Conductor exited with status 1
```

**Comment by tianon** [comment]
I can't seem to reproduce: :confused:
```console

$ docker pull debian:stretch
stretch: Pulling from library/debian
Digest: sha256:6ccbcbf362dbc4add74711cb774751b59cdfd7aed16c3c29aaecbea871952fe0
Status: Image is up to date for debian:stretch

$ docker run -it --rm debian:stretch
root@30dafceccd8d:/# apt-get update -qq
root@30dafceccd8d:/# apt-get install -qqy --no-install-recommends python3
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libssl1.1:amd64.
(Reading database ... 6491 files and directories currently installed.)
Preparing to unpack .../00-libssl1.1_1.1.0f-3_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.0f-3) ...
Selecting previously unselected package libpython3.5-minimal:amd64.
Preparing to unpack .../01-libpython3.5-minimal_3.5.3-1_amd64.deb ...
Unpacking libpython3.5-minimal:amd64 (3.5.3-1) ...
Selecting previously unselected package libexpat1:amd64.
Preparing to unpack .../02-libexpat1_2.2.0-2+deb9u1_amd64.deb ...
Unpacking libexpat1:amd64 (2.2.0-2+deb9u1) ...
Selecting previously unselected package python3.5-minimal.
Preparing to unpack .../03-python3.5-minimal_3.5.3-1_amd64.deb ...
Unpacking python3.5-minimal (3.5.3-1) ...
Selecting previously unselected package python3-minimal.
Preparing to unpack .../04-python3-minimal_3.5.3-1_amd64.deb ...
Unpacking python3-minimal (3.5.3-1) ...
Selecting previously unselected package mime-support.
Preparing to unpack .../05-mime-support_3.60_all.deb ...
Unpacking mime-support (3.60) ...
Selecting previously unselected package libmpdec2:amd64.
Preparing to unpack .../06-libmpdec2_2.4.2-1_amd64.deb ...
Unpacking libmpdec2:amd64 (2.4.2-1) ...
Selecting previously unselected package readline-common.
Preparing to unpack .../07-readline-common_7.0-3_all.deb ...
Unpacking readline-common (7.0-3) ...
Selecting previously unselected package libreadline7:amd64.
Preparing to unpack .../08-libreadline7_7.0-3_amd64.deb ...
Unpacking libreadline7:amd64 (7.0-3) ...
Selecting previously unselected package libsqlite3-0:amd64.
Preparing to unpack .../09-libsqlite3-0_3.16.2-5_amd64.deb ...
Unpacking libsqlite3-0:amd64 (3.16.2-5) ...
Selecting previously unselected package libpython3.5-stdlib:amd64.
Preparing to unpack .../10-libpython3.5-stdlib_3.5.3-1_amd64.deb ...
Unpacking libpython3.5-stdlib:amd64 (3.5.3-1) ...
Selecting previously unselected package python3.5.
Preparing to unpack .../11-python3.5_3.5.3-1_amd64.deb ...
Unpacking python3.5 (3.5.3-1) ...
Selecting previously unselected package libpython3-stdlib:amd64.
Preparing to unpack .../12-libpython3-stdlib_3.5.3-1_amd64.deb ...
Unpacking libpython3-stdlib:amd64 (3.5.3-1) ...
Selecting previously unselected package dh-python.
Preparing to unpack .../13-dh-python_2.20170125_all.deb ...
Unpacking dh-python (2.20170125) ...
Setting up libssl1.1:amd64 (1.1.0f-3) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libpython3.5-minimal:amd64 (3.5.3-1) ...
Setting up libexpat1:amd64 (2.2.0-2+deb9u1) ...
Setting up python3.5-minimal (3.5.3-1) ...
Setting up python3-minimal (3.5.3-1) ...
Selecting previously unselected package python3.
(Reading database ... 7484 files and directories currently installed.)
Preparing to unpack .../python3_3.5.3-1_amd64.deb ...
Unpacking python3 (3.5.3-1) ...
Setting up readline-common (7.0-3) ...
Setting up mime-support (3.60) ...
Setting up libreadline7:amd64 (7.0-3) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Setting up libsqlite3-0:amd64 (3.16.2-5) ...
Setting up libmpdec2:amd64 (2.4.2-1) ...
Setting up libpython3.5-stdlib:amd64 (3.5.3-1) ...
Setting up python3.5 (3.5.3-1) ...
Setting up libpython3-stdlib:amd64 (3.5.3-1) ...
Setting up dh-python (2.20170125) ...
Setting up python3 (3.5.3-1) ...
running python rtupdate hooks for python3.5...
running python post-rtupdate hooks for python3.5...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
root@30dafceccd8d:/# python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 2 + 2
4
>>> 
```

**Comment by roosemberth** [comment]
This issue concerns ansible-container: https://github.com/ansible/ansible-container/issues/551
Sorry for the inconvenience
